# Lecture Four - June 13th 2017

* Let's talk about [Against Cleaning](http://curatingmenus.org/articles/against-cleaning/)
* Quick review of last week
* Diving deeper into Pandas

## Against Cleaning

* What did yinz think of that article?
* Are they being worryworts or is there something important to consider about "data cleaning"

## A quick review of last week

* Series
* Data Frames
* Index

### Series

* One-dimensional data structure
* Mother was a list, father was a dictionary
* Dictionary keys become the Series *index*

In [1]:
# Import pandas so we can do stuff
import pandas as pd

In [2]:
# create a Series from a list with implicit index
my_list = [0.25, 0.5, 0.75, 1.0]
data = pd.Series(my_list) # "the constructor"
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
# create a Series from a list with explicit index
my_list = [0.25, 0.5, 0.75, 1.0]
data = pd.Series(my_list, index=[1,2,3,4])
data

1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

* you can create an index-by-one, but slicing is still index-by-zero

In [4]:
# get the item with the index number `
data[1]

0.25

In [5]:
# get the items at the 2nd and 3rd location
data[1:3]

2    0.50
3    0.75
dtype: float64

In [6]:
# create a Series from a dictionary where keys become the index
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [7]:
# slicing names instead of numbers
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

### Dataframes

* Two-dimensional data structure
* Made of columns, where each column is a Series
* A spreadsheet, but in Python

In [8]:
# Quickly create two series with the same index, but different values 
population = pd.Series({'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135})
area = pd.Series({'Illinois': 149995, 'California': 423967, 
             'Texas': 695662, 'Florida': 170312, 
             'New York': 141297})

# now moosh them together into a dataframe
states = pd.DataFrame({'population': population,
                       'area': area})
states

              area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

* Reading CSV files into Dataframes

In [9]:
parsed_email_data  = pd.read_csv("parsed-emails.csv")
parsed_email_data.head(10) #only display the first 10 emails

                      address dayofweek month  day      time  year
0  stephen.marquard@uct.ac.za       Sat   Jan    5  09:14:16  2008
1    louis@media.berkeley.edu       Fri   Jan    4  18:10:48  2008
2             zqian@umich.edu       Fri   Jan    4  16:10:39  2008
3            rjlowe@iupui.edu       Fri   Jan    4  15:46:24  2008
4             zqian@umich.edu       Fri   Jan    4  15:03:18  2008
5            rjlowe@iupui.edu       Fri   Jan    4  14:50:18  2008
6              cwen@iupui.edu       Fri   Jan    4  11:37:30  2008
7              cwen@iupui.edu       Fri   Jan    4  11:35:08  2008
8           gsilver@umich.edu       Fri   Jan    4  11:12:37  2008
9           gsilver@umich.edu       Fri   Jan    4  11:11:52  2008

## Vectorized string operations - remember to use ".str."
* Using *vectorized string operations* to split email addresses, carve out domain names, and create a new column with those results

In [10]:
parsed_email_data['institution'] = parsed_email_data['address'].str.split("@").str.get(1)
parsed_email_data.head(10)

,address,dayofweek,month,day,time,year,institution
0,stephen.marquard@uct.ac.za,Sat,Jan,5,09:14:16,2008,uct.ac.za
1,louis@media.berkeley.edu,Fri,Jan,4,18:10:48,2008,media.berkeley.edu
2,zqian@umich.edu,Fri,Jan,4,16:10:39,2008,umich.edu
3,rjlowe@iupui.edu,Fri,Jan,4,15:46:24,2008,iupui.edu
4,zqian@umich.edu,Fri,Jan,4,15:03:18,2008,umich.edu
5,rjlowe@iupui.edu,Fri,Jan,4,14:50:18,2008,iupui.edu
6,cwen@iupui.edu,Fri,Jan,4,11:37:30,2008,iupui.edu
7,cwen@iupui.edu,Fri,Jan,4,11:35:08,2008,iupui.edu
8,gsilver@umich.edu,Fri,Jan,4,11:12:37,2008,umich.edu
9,gsilver@umich.edu,Fri,Jan,4,11:11:52,2008,umich.edu

* Selecting a single column and use the [`value_counts()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) method to count unique values
* ".value_counts()" works only on series (e.g., a single column of a DataFrame).

In [11]:
parsed_email_data['institution'].value_counts()

iupui.edu             8
umich.edu             7
uct.ac.za             6
media.berkeley.edu    4
caret.cam.ac.uk       1
gmail.com             1
Name: institution, dtype: int64

## Diving Deeper into Pandas

* So far we have only really scratched the surface of what Pandas can do
* Merging Datasets together
* Multi-level indexing
* Split-Apply-Combine
* Working with Timeseries

### Merging Data

* Bringing disparate datasets together is one of the more powerful features of Pandas
* Like with Python lists, you can `append()` and `concat()` Pandas `Series` and `Dataframes`
* These functions work best for simple cases

_REMEMBER TO PUT SERIES INSIDE LIST BRACKETS FOR CONCAT FUNCTION_

In [12]:
# concatinate two series together
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [13]:
# concatinate two dataframes
df1 = pd.DataFrame({"A":["A1", "A2"],
                    "B":["B1","B2"]},index=[1,2])
df2 = pd.DataFrame({"A":["A3", "A4"],
                    "B":["B3","B4"]},index=[3,4])
pd.concat([df1,df2])

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [14]:
# concatinate dataframes horizontally
df1 = pd.DataFrame({"A":["A1", "A2"],
                    "B":["B1","B2"]},index=[1,2])
df2 = pd.DataFrame({"C":["C1", "C2"],
                    "D":["D1","D2"]},index=[1,2])
pd.concat([df1,df2], axis="col")

    A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [15]:
# What happens when indexes don't line up
df1 = pd.DataFrame({"A":["A1", "A2"],
                    "B":["B1","B2"]},index=[1,2])
df2 = pd.DataFrame({"A":["A3", "A4"],
                    "B":["B3","B4"]},index=[3,4])
pd.concat([df1,df2], axis="col")

     A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

## Hierarchical indexing

In [16]:
# create a hierarchical index
df1 = pd.DataFrame({"A":["A1", "A2"],
                    "B":["B1","B2"]},index=[1,2])
df2 = pd.DataFrame({"A":["A3", "A4"],
                    "B":["B3","B4"]},index=[3,4])
pd.concat([df1,df2], keys=["df1", 'df2'])

        A   B
df1 1  A1  B1
    2  A2  B2
df2 3  A3  B3
    4  A4  B4

### Merging and Joining

* While `concat()` is useful it lacks the power to do complex data merging
* For example, I have two tables of different data but one overlapping column
* This is where the `merge()` function becomes useful because it lets you *join* datasets
* The concept of "join" has lots of theory and is a richly developed method for *joining* data

#### One-to-one joins

In [26]:
# create two dataframes with one shared column
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue', 'Jason'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR', 'Student Health']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [27]:
# display df1
df1

  employee           group
0      Bob      Accounting
1     Jake     Engineering
2     Lisa     Engineering
3      Sue              HR
4    Jason  Student Health

In [20]:
# display df2
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [28]:
# merge df1 and df2 into a new dataframe df3
df3 = pd.merge(df1, df2, on='employee', how='outer') # default is how='inner'
df3

  employee           group  hire_date
0      Bob      Accounting       2008
1     Jake     Engineering       2012
2     Lisa     Engineering       2004
3      Sue              HR       2014
4    Jason  Student Health        NaN

* The new dataframe `df3` now has all of the data from df1 and df2
* The `merge` function automatically connected the two tables on the "employees" column
* But what happens when your data don't line up?

#### Many-to-one joins

* Sometimes there isn't a one to one relationshp between rows in the two datasets
* A *many-to-one* join lets you combine these datasets

In [29]:
# make another dataframe about the supervisor for each group
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [30]:
# Merge df3 from above with the supervisor info in df4
pd.merge(df3,df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

* Notice how the information about Guido, the manager for Engineering, is repeated.
* While this might seem like duplicated data, it makes it easier to quickly look up Jake and Lisa's supervisor without consulting multiple tables

#### Many-to-many joins

* Let's combine the employee information with skills information
* Notice there isn't a one to one or even a one to many relationship between these tables
* Each group can have multiple skills, so **what do you think will happen?**

In [ ]:
# Use the employee table specified above
df1

In [31]:
# create a new dataframe with skills information
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR', 'Library'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization', 'nunchucks']})
df5

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
6      Library     nunchucks

In [32]:
pd.merge(df1, df5)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

* Amazing, Pandas merge capabilities are very useful
* But what do you do if the names of your columns don't match?
* You could change column names...
* But that is crazy! Just use the `left_on` and `right_on` parameters to the `merge()` function

In [ ]:
# Use the employee table specified above
df1

In [33]:
# Create a new salary table, but use "name" instead of "employee" for the column index
df3 = df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
df3

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [34]:
# lets try and merge them without specifying what to merge on
pd.merge(df1, df3)

MergeError: No common columns to perform merge on

* What are the column names I should specify?

In [36]:
# Now lets specify the column name 
pd.merge(df1, df3, left_on='employee', right_on='name' )

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

* Notice we now have a redundant employee/name column, this is a by-product of merging different columns
* If you want to get rid of it you can use the `drop` method

In [41]:
# drop the name column, axis=1 means axis='col', which is confusing
pd.merge(df1, df3, left_on="employee", right_on="name" ).drop('name', axis=1) #axis=1 is column (=0 is row)
#pd.merge(df1, df3, left_on="employee", right_on="name" ).drop(0, axis=0) #axis=0 is row

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

### Splitting Data with GroupBy


* A common pattern in data analysis is splitting data by a key and then performing some math on all of the values with that key and finally combining it all back together
* This is commonly known in data circles as *split, apply, combine*

In [42]:
# create a dataframe to illustrate GroupBy
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [ ]:
# Dataframes have a method, groupby(), that takes a column name be be the grouping key
df.groupby('key')

* Cool, but what is that? Well, we need to tell Pandas what to *do* with the groups
* This is where we get to the *apply* step
* We need to specify what kind of aggregation, transformation, or computation to perform on the group

In [43]:
# Tell pandas to add up all of the values for each key
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

The following table summarizes some other built-in Pandas aggregations:

| Aggregation              | Description                     |
|--------------------------|---------------------------------|
| ``count()``              | Total number of items           |
| ``size()``               | Total number of items w/ NaNs   |
| ``first()``, ``last()``  | First and last item             |
| ``mean()``, ``median()`` | Mean and median                 |
| ``min()``, ``max()``     | Minimum and maximum             |
| ``std()``, ``var()``     | Standard deviation and variance |
| ``mad()``                | Mean absolute deviation         |
| ``prod()``               | Product of all items            |
| ``sum()``                | Sum of all items                |

These are all methods of ``DataFrame`` and ``Series`` objects.

#### Exercise
* Create a new dataframe with different keys and values, then try the aggregations above

In [63]:
#!wget https://github.com/colditzjb/YelpEpi/blob/master/data/2016-09-02.csv
yelpMonth = pd.read_csv('2016-09-02.csv')
yelpMonth.head(10) #only display the first 10
    
# Modify this dataframe to put your own values in
#df = pd.DataFrame({'key': ['vape', 'vape', 'ecig', 'vapor', 'vape'],
#                   'data': [1,3,4,1,5]}, columns=['key', 'data'])

yelpMonth.groupby("key").size()

CParserError: Error tokenizing data. C error: Expected 1 fields in line 108, saw 3

### Working with Time

* One of the most powerful features of Pandas is its time series functionality
* Dates and time are a Python and Pandas data type (like integers and strings)
* By using the `datetime` data types you can do advanced, time-centric analysis
* One thing to remember about computers is they are *very* specific
    * *Time stamps* - a specific moment in time (July 4th, 2017 at 7:52am and 34 seconds)
    * *Time intervals* - a length of time with start and end points (The year 2017)
    * *Time duration* - a specific length of time (a year, a month, a day)

In [51]:
# Datetime in Vanilla Python
import datetime

date = datetime.datetime(year=2017, month=6, day=13)
date

datetime.datetime(2017, 6, 13, 0, 0)

In [52]:
# what is that date's month?
date.month

6

In [ ]:
# what is that date's day?
date.day

In [62]:
# use the parser function in the datautil library to parse human dates
from dateutil import parser
date = parser.parse("4th of July, 2017")
#date.weekday()
date.strftime('%A')

'Tuesday'

In [ ]:
# get the month
date.month

* You can use [*string format codes*](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) for printing dates and time in different formats (especially useful for making human readable dates)
* Pass a format string to the `strftime()` method to print out a pretty date

In [ ]:
# Get the weekday 
date.strftime("%A")

In [ ]:
## Try some of the different string format codes and see what happens
date.

In [ ]:
## Try combining a few of them together with punctuation too
date.

### Working with time in Pandas

* Just like how Pandas has its own datatypes for numbers, Pandas has its own dates and times (to support more granularity)
* If you have a lot of dates, it is often useful to use the Pandas functions over the native Python functions
* Pandas is most powerful when you index by time using the `DatetimeIndex`

In [ ]:
# Create a Series with a DateTime index
index = pd.DatetimeIndex(['2014-03-04', '2014-08-04',
                          '2015-04-04', '2015-09-04',
                          '2016-01-01', '2016-02-16'])
data = pd.Series([0, 1, 2, 3, 4, 5], index=index)
data

In [ ]:
# grab the value for a specific day
data["2015-04-04"]

In [ ]:
# grab a slice between two dates
data['2014-08-01':'2016-01']

In [ ]:
# give me everything from 2015
data['2015']

* Pandas has some functions to make parsing dates easy too

In [ ]:
# use the to_datetime function instead of the parser function
date = pd.to_datetime("4th of July, 2017")
date

In [ ]:
# use string format codes to get the weekday
date.strftime("%A")

In [65]:
# give me today's date
today = pd.to_datetime("Today")
today

Timestamp('2017-06-13 00:00:00')

#### Exercise
* Use the [*string format codes*](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) to print today's date in the "YYYY-MM-DD" format. HINT: You will have to combine multiple codes and dashes

In [68]:
# Replace the ??? with the write string format code
print(today.strftime('%Y-%m-%d'))

2017-06-13

In [70]:
#yelpMo = pd.read_csv('https://github.com/colditzjb/YelpEpi/blob/master/data/2016-09-02.csv')

### Playing with time on real data

* Let's look at the [311 data for the city of Pittsburgh](https://data.wprdc.org/dataset/311-data) from the WPRDC
* You can either download the CSV file or give the URL directly to Pandas

In [72]:
# load the 311 data directly from the WPRDC
pgh_311_data = pd.read_csv("https://data.wprdc.org/datastore/dump/40776043-ad00-40f5-9dc8-1fde865ff571")
pgh_311_data.head()

,_id,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
0,41660,49918,2016-02-23T10:34:00,Building Maintenance,Control Panel,"Permits, Licenses and Inspections",Spring Garden,1,24,42003241200,1,NaN,1,1-5,-79.991347,40.460229,APPROXIMATE
1,41661,49919,2016-02-23T10:36:00,Potholes,Website,DPW - Street Maintenance,Duquesne Heights,2,19,42003191100,5,NaN,3,4-1,-80.019481,40.433648,EXACT
2,41662,49920,2016-02-23T10:36:00,Junk Vehicles,Call Center,"Permits, Licenses and Inspections",Esplen,2,20,42003562500,5,NaN,6,1-27,-80.056441,40.462330,APPROXIMATE
3,41663,49922,2016-02-23T10:38:00,Vacant Building,Control Panel,"Permits, Licenses and Inspections",Crawford-Roberts,6,3,42003030500,3,NaN,2,2-1,-79.980854,40.441690,EXACT
4,41664,49923,2016-02-23T10:38:00,Sewers,Call Center,Pittsburgh Water and Sewer Authority,East Hills,9,13,42003130600,2,NaN,5,3-17,-79.884784,40.455226,EXACT

In [73]:
# Inspect the dataframe and Pandas automatic data type detection
pgh_311_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150609 entries, 0 to 150608
Data columns (total 17 columns):
_id                      150609 non-null int64
REQUEST_ID               150609 non-null int64
CREATED_ON               150609 non-null object
REQUEST_TYPE             150609 non-null object
REQUEST_ORIGIN           150609 non-null object
DEPARTMENT               149827 non-null object
NEIGHBORHOOD             141902 non-null object
COUNCIL_DISTRICT         142087 non-null float64
WARD                     141924 non-null float64
TRACT                    142751 non-null float64
PUBLIC_WORKS_DIVISION    141925 non-null float64
PLI_DIVISION             59348 non-null float64
POLICE_ZONE              141894 non-null float64
FIRE_ZONE                142039 non-null object
X                        144468 non-null float64
Y                        144468 non-null float64
GEO_ACCURACY             150609 non-null object
dtypes: float64(8), int64(2), object(7)
memory usage: 16.7+ MB

* Ok, now we have the data, but we need it to be indexed by date
* **What column has the date information?**
* **What format do you think that column is currently in?**
* **What function might we use to convert that column into dates?**

In [ ]:
#today = pd.to_datetime()

In [74]:
# convert the "CREATED_ON" column to dates
pd.to_datetime(pgh_311_data['CREATED_ON']).head()

0   2016-02-23 10:34:00
1   2016-02-23 10:36:00
2   2016-02-23 10:36:00
3   2016-02-23 10:38:00
4   2016-02-23 10:38:00
Name: CREATED_ON, dtype: datetime64[ns]

* We can convert the "CREATED_ON" column to Pandas `datetime` objects
* Now we have to set that to the dataframe's index

In [75]:
# set the index of pgh_311_data to be the parsed dates in the "CREATED_ON" column
pgh_311_data.index = pd.to_datetime(pgh_311_data['CREATED_ON'])
pgh_311_data.head()

,_id,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
CREATED_ON,,,,,,,,,,,,,,,,,
2016-02-23 10:34:00,41660,49918,2016-02-23T10:34:00,Building Maintenance,Control Panel,"Permits, Licenses and Inspections",Spring Garden,1,24,42003241200,1,NaN,1,1-5,-79.991347,40.460229,APPROXIMATE
2016-02-23 10:36:00,41661,49919,2016-02-23T10:36:00,Potholes,Website,DPW - Street Maintenance,Duquesne Heights,2,19,42003191100,5,NaN,3,4-1,-80.019481,40.433648,EXACT
2016-02-23 10:36:00,41662,49920,2016-02-23T10:36:00,Junk Vehicles,Call Center,"Permits, Licenses and Inspections",Esplen,2,20,42003562500,5,NaN,6,1-27,-80.056441,40.462330,APPROXIMATE
2016-02-23 10:38:00,41663,49922,2016-02-23T10:38:00,Vacant Building,Control Panel,"Permits, Licenses and Inspections",Crawford-Roberts,6,3,42003030500,3,NaN,2,2-1,-79.980854,40.441690,EXACT
2016-02-23 10:38:00,41664,49923,2016-02-23T10:38:00,Sewers,Call Center,Pittsburgh Water and Sewer Authority,East Hills,9,13,42003130600,2,NaN,5,3-17,-79.884784,40.455226,EXACT

* Do'h, now we have CREATED_ON twice, that isn't very tidy
* We can also skip this extra conversion step entirely by specifying the index column and date parsing in `read_csv()` function call.

In [ ]:
# load the 311 data directly from the WPRDC and parse dates directly
pgh_311_data = pd.read_csv("https://data.wprdc.org/datastore/dump/40776043-ad00-40f5-9dc8-1fde865ff571",
                           index_col="CREATED_ON", 
                           parse_dates=True)
pgh_311_data.head()

In [ ]:
pgh_311_data.info()

* Now that the dataframe has been indexed by time we can select 311 complains by time

In [76]:
# Select 311 complaints on January 1st, 2016
pgh_311_data['2016-01-01']

,_id,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
CREATED_ON,,,,,,,,,,,,,,,,,
2016-01-01 01:14:00,30998,39132,2016-01-01T01:14:00,Potholes,Website,DPW - Street Maintenance,South Side Flats,3,17,42003170200,4,NaN,3,4-24,-79.984121,40.430102,EXACT
2016-01-01 02:22:00,30999,39133,2016-01-01T02:22:00,Curb Cuts,Website,DPW - Permits,Beechview,4,19,42003191600,5,NaN,6,4-28,-80.021355,40.412577,EXACT
2016-01-01 12:21:00,31000,39135,2016-01-01T12:21:00,Excessive Noise/Disturbances,Website,Police - Zones 1-6,Carrick,4,29,42003290400,4,NaN,3,4-15,-79.980177,40.388505,APPROXIMATE
2016-01-01 18:45:00,31001,39136,2016-01-01T18:45:00,Sidewalk - Snow/Ice Covered,Website,DPW - Permits,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.056914,40.440647,APPROXIMATE
2016-01-01 18:51:00,31002,39137,2016-01-01T18:51:00,Sidewalk - Snow/Ice Covered,Website,DPW - Permits,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.056794,40.440767,APPROXIMATE
2016-01-01 19:03:00,31003,39138,2016-01-01T19:03:00,"Court, Basketball or Tennis",Website,DPW - Park Maintenance,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.055769,40.439332,EXACT
2016-01-01 19:22:00,31004,39139,2016-01-01T19:22:00,"Court, Basketball or Tennis",Website,DPW - Park Maintenance,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.055990,40.439711,EXACT
2016-01-01 19:31:00,31005,39140,2016-01-01T19:31:00,Paving Concern/Problem,Website,DPW - Asphalt,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.055827,40.439602,EXACT
2016-01-01 20:04:00,31006,39141,2016-01-01T20:04:00,Collapsed Catch Basin,Website,Pittsburgh Water and Sewer Authority,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.055873,40.439591,EXACT
2016-01-01 20:08:00,31007,39142,2016-01-01T20:08:00,Collapsed Catch Basin,Website,Pittsburgh Water and Sewer Authority,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.055873,40.439591,EXACT
2016-01-01 20:30:00,31008,39143,2016-01-01T20:30:00,Collapsed Catch Basin,Website,Pittsburgh Water and Sewer Authority,Crafton Heights,2,28,42003281500,5,NaN,6,1-18,-80.055873,40.439591,EXACT
2016-01-01 20:42:00,31009,39144,2016-01-01T20:42:00,Illegal Parking,Website,Police - Zones 1-6,South Side Slopes,3,16,42003160800,4,NaN,3,4-22,-79.970940,40.422801,APPROXIMATE
2016-01-01 20:42:00,31010,39145,2016-01-01T20:42:00,City Facility,Website,DPW - Facilities,Westwood,2,28,42003563100,5,NaN,6,1-18,-80.053268,40.431461,EXACT
2016-01-01 20:46:00,31011,39146,2016-01-01T20:46:00,No Parking Variance,Website,DPW - Permits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2016-01-01 20:51:00,31012,39147,2016-01-01T20:51:00,Towed Vehicle,Website,Police - AVU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2016-01-01 20:59:00,31013,39149,2016-01-01T20:59:00,Traffic,Website,Police - Zones 1-6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2016-01-01 21:07:00,31014,39150,2016-01-01T21:07:00,Gang Activity,Website,Police - Zones 1-6,Central Business District,6,2,42003020100,6,NaN,2,1-4,-79.995732,40.439622,APPROXIMATE
2016-01-01 21:09:00,31015,39151,2016-01-01T21:09:00,Other (please describe),Website,Animal Care & Control,Central Business District,6,2,42003020100,6,NaN,2,1-4,-79.995901,40.439453,APPROXIMATE
2016-01-01 21:14:00,31016,39152,2016-01-01T21:14:00,Water Pressure,Website,Pittsburgh Water and Sewer Authority,Central Business District,6,2,42003020100,6,NaN,2,1-4,-79.997302,40.438702,EXACT
2016-01-01 21:23:00,31017,39153,2016-01-01T21:23:00,Abandoned Vehicle (parked on street),Website,Police - AVU,South Oakland,6,4,42003040900,3,NaN,4,2-10,-79.962996,40.435360,APPROXIMATE
2016-01-01 23:32:00,31018,39154,2016-01-01T23:32:00,Speeding,Report2Gov iOS,Police - Zones 1-6,Banksville,2,20,42003202300,5,NaN,6,4-9,-80.043030,40.404907,EXACT

In [ ]:
# Select the times just around the new years celebration
pgh_311_data["2015-12-31 20:00:00":"2016-01-01 02:00:00"]

* Someone clearly had a very roudy new years

#### Exercise

* Using the timeseries index selection, select the complaints made today but don't hard-code the date
* Write your code so it will work on any day you execute it

In [78]:
# Write your code here
pgh_311_data["2017-06-13"]

,_id,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
CREATED_ON,,,,,,,,,,,,,,,,,
2017-06-13 00:33:00,150451,161367,2017-06-13T00:33:00,Potholes,Website,DPW - Street Maintenance,Carrick,4,29,42003290400,4,29,3,4-23,-79.982837,40.386519,EXACT
2017-06-13 08:17:00,150458,161374,2017-06-13T08:17:00,Pruning (city tree),Website,DPW - Forestry Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2017-06-13 05:01:00,150454,161370,2017-06-13T05:01:00,Rodent control,Website,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020227,40.392072,APPROXIMATE
2017-06-13 06:38:00,150455,161371,2017-06-13T06:38:00,Boat/Trailer on Street,Website,Police - Zones 1-6,Elliott,2,20,42003562600,5,20,6,1-17,-80.036531,40.444124,APPROXIMATE
2017-06-13 07:11:00,150456,161372,2017-06-13T07:11:00,Dumpster (on Street),Report2Gov Android,DPW - Permits,Knoxville,3,30,42003300100,4,30,3,4-7,-79.994010,40.411830,EXACT
2017-06-13 08:54:00,150462,161379,2017-06-13T08:54:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Homewood South,9,13,42003130400,2,13,5,3-17,-79.888215,40.452316,EXACT
2017-06-13 08:55:00,150463,161380,2017-06-13T08:55:00,Drug Enforcement,Call Center,Police - Zones 1-6,Manchester,6,21,42003210700,1,21,1,1-8,-80.023541,40.453031,APPROXIMATE
2017-06-13 08:56:00,150464,161381,2017-06-13T08:56:00,Dead Animal,Call Center,Animal Care & Control,Brighton Heights,1,27,42003270800,1,27,1,1-14,-80.033914,40.484603,EXACT
2017-06-13 08:57:00,150465,161382,2017-06-13T08:57:00,Abandoned Vehicle (parked on street),Report2Gov iOS,Police - AVU,Polish Hill,7,6,42003060500,6,6,2,2-6,-79.969192,40.456809,APPROXIMATE
2017-06-13 09:00:00,150467,161384,2017-06-13T09:00:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",South Side Slopes,3,17,42003170600,4,17,3,4-22,-79.985377,40.420779,EXACT
2017-06-13 08:58:00,150466,161383,2017-06-13T08:58:00,Barking Dog,Call Center,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020459,40.392102,APPROXIMATE
2017-06-13 08:10:00,150457,161373,2017-06-13T08:10:00,Refuse Violations,Website,DPW - Refuse,Marshall-Shadeland,1,27,42003271500,1,27,1,1-14,-80.027344,40.470608,APPROXIMATE
2017-06-13 08:52:00,150460,161377,2017-06-13T08:52:00,Litter,Call Center,DPW - Street Maintenance,Mount Washington,2,19,42003191500,5,19,3,4-27,-80.009787,40.421818,EXACT
2017-06-13 09:09:00,150468,161385,2017-06-13T09:09:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Carrick,4,29,42003290100,4,29,3,4-23,-79.995821,40.402175,EXACT
2017-06-13 08:50:00,150459,161376,2017-06-13T08:50:00,Replace/Repair a Sign,Website,DPW - Traffic,Crafton Heights,2,28,42003281400,5,28,6,1-16,-80.058813,40.449366,EXACT
2017-06-13 09:13:00,150469,161386,2017-06-13T09:13:00,"Traffic or Pedestrian Signal, Repair",Report2Gov iOS,DPW - Traffic,Knoxville,3,30,42003300100,4,30,3,4-6,-79.990578,40.415119,EXACT
2017-06-13 09:17:00,150470,161387,2017-06-13T09:17:00,Replace/Repair a Sign,Call Center,DPW - Traffic,Mount Washington,2,19,42003191400,5,19,3,4-27,-80.013081,40.422898,EXACT
2017-06-13 09:22:00,150472,161389,2017-06-13T09:22:00,Potholes,Call Center,DPW - Street Maintenance,Beechview,4,19,42003191600,5,19,6,4-28,-80.027121,40.409417,EXACT
2017-06-13 10:11:00,150493,161414,2017-06-13T10:11:00,Potholes,Call Center,DPW - Street Maintenance,Brookline,4,19,42003191900,4,19,6,4-26,-80.025885,40.396641,EXACT
2017-06-13 09:21:00,150471,161388,2017-06-13T09:21:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Beechview,4,19,42003191600,5,19,6,4-28,-80.027162,40.409320,EXACT
2017-06-13 09:30:00,150474,161390,2017-06-13T09:30:00,Water/Drinking Fountains,Website,DPW - Facilities,Shadyside,8,7,42003070800,2,7,4,3-13,-79.915491,40.455945,EXACT
2017-06-13 09:30:00,150473,161391,2017-06-13T09:30:00,Pruning (city tree),Website,DPW - Forestry Division,Squirrel Hill South,5,14,42003141400,3,14,4,2-15,-79.920236,40.423276,EXACT
2017-06-13 09:32:00,150476,161393,2017-06-13T09:32:00,Pruning (city tree),Website,DPW - Forestry Division,Squirrel Hill South,5,14,42003141400,3,14,4,2-15,-79.920022,40.423049,EXACT
2017-06-13 09:32:00,150475,161392,2017-06-13T09:32:00,Building Maintenance,Call Center,"Permits, Licenses and Inspections",Perry South,6,26,42003261500,1,26,1,1-12,-80.017832,40.470168,APPROXIMATE
2017-06-13 09:33:00,150477,161394,2017-06-13T09:33:00,Pruning (city tree),Website,DPW - Forestry Division,Squirrel Hill South,5,14,42003140800,3,14,4,2-18,-79.916081,40.437882,EXACT
2017-06-13 09:34:00,150478,161395,2017-06-13T09:34:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Central Oakland,3,4,42003040500,3,4,4,2-14,-79.955156,40.437495,EXACT
2017-06-13 09:36:00,150479,161396,2017-06-13T09:36:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Central Oakland,3,4,42003040500,3,4,4,2-14,-79.955204,40.437804,EXACT
2017-06-13 09:36:00,150480,161397,2017-06-13T09:36:00,Dead Animal,Website,Animal Care & Control,NaN,1,NaN,42003981200,NaN,NaN,NaN,NaN,-80.003643,40.446359,EXACT
2017-06-13 09:43:00,150482,161402,2017-06-13T09:43:00,Early Set Out,Website,DPW - Refuse,Allentown,3,18,42003180300,4,18,3,4-6,-79.992464,40.421079,APPROXIMATE
2017-06-13 09:58:00,150484,161404,2017-06-13T09:58:00,Overgrowth,Call Center,DPW - Street Maintenance,Elliott,2,20,42003562600,5,20,6,1-17,-80.034014,40.443576,EXACT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-06-13 12:30:00,150583,161502,2017-06-13T12:30:00,Question,Call Center,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 12:31:00,150584,161503,2017-06-13T12:31:00,Missed Pick Up,Call Center,DPW - Refuse,Terrace Village,6,5,42003051000,3,5,2,2-10,-79.971256,40.441842,APPROXIMATE
2017-06-13 12:32:00,150585,161504,2017-06-13T12:32:00,Question,Call Center,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 12:33:00,150586,161505,2017-06-13T12:33:00,Refuse Violations,Call Center,DPW - Refuse,Beechview,4,19,42003192000,5,19,6,4-28,-80.029822,40.400889,APPROXIMATE
2017-06-13 12:35:00,150587,161506,2017-06-13T12:35:00,Weeds/Debris,Website,"Permits, Licenses and Inspections",Beechview,4,19,42003192000,5,19,6,4-28,-80.019280,40.407810,EXACT
2017-06-13 12:37:00,150588,161507,2017-06-13T12:37:00,Potholes,Call Center,DPW - Street Maintenance,Beechview,4,19,42003191600,5,19,6,4-28,-80.029274,40.411929,EXACT
2017-06-13 12:39:00,150589,161508,2017-06-13T12:39:00,Potholes,Call Center,DPW - Street Maintenance,Shadyside,8,7,42003070500,2,7,4,3-11,-79.927936,40.456647,EXACT
2017-06-13 12:39:00,150590,161509,2017-06-13T12:39:00,Potholes,Call Center,DPW - Street Maintenance,Carrick,4,29,42003290100,4,29,3,4-23,-79.994601,40.394256,EXACT
2017-06-13 12:45:00,150591,161510,2017-06-13T12:45:00,Potholes,Call Center,DPW - Street Maintenance,Lincoln-Lemington-Belmar,9,12,42003120300,2,12,5,3-15,-79.904207,40.466934,EXACT
2017-06-13 12:45:00,150592,161512,2017-06-13T12:45:00,Leak,Call Center,Pittsburgh Water and Sewer Authority,Lincoln-Lemington-Belmar,9,12,42003120300,2,12,5,3-15,-79.904241,40.467019,EXACT
2017-06-13 12:45:00,150593,161511,2017-06-13T12:45:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Bloomfield,7,8,42003080600,2,8,5,3-23,-79.942270,40.461680,EXACT
2017-06-13 12:46:00,150594,161513,2017-06-13T12:46:00,Illegal Dumping,Call Center,DPW - Permits,South Side Slopes,3,17,42003170600,4,17,3,4-3,-79.980075,40.422489,APPROXIMATE
2017-06-13 12:47:00,150595,161514,2017-06-13T12:47:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",West Oakland,6,4,42003040200,3,4,4,2-10,-79.967355,40.439866,EXACT
2017-06-13 12:48:00,150596,161515,2017-06-13T12:48:00,Overgrowth,Call Center,DPW - Street Maintenance,Carrick,4,29,42003290400,4,29,3,4-23,-79.978259,40.384019,EXACT
2017-06-13 12:49:00,150597,161516,2017-06-13T12:49:00,Potholes,Call Center,DPW - Street Maintenance,Lincoln Place,5,31,42003310200,3,31,4,4-20,-79.912357,40.370192,EXACT
2017-06-13 12:50:00,150598,161518,2017-06-13T12:50:00,"Permits, Licenses and Inspections",Website,"Permits, Licenses and Inspections",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 12:50:00,150599,161517,2017-06-13T12:50:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",South Side Slopes,3,16,42003160800,4,16,3,4-22,-79.974084,40.421621,EXACT
2017-06-13 12:51:00,150600,161519,2017-06-13T12:51:00,Dead Animal,Twitter,Animal Care & Control,NaN,1,NaN,42003563200,NaN,NaN,NaN,NaN,-80.003425,40.445898,EXACT
2017-06-13 12:53:00,150601,161520,2017-06-13T12:53:00,Traffic,Call Center,DPW - Transportation & Engineering,South Oakland,3,4,42003980800,3,4,4,2-2,-79.959240,40.431176,EXACT
2017-06-13 12:53:00,150602,161521,2017-06-13T12:53:00,CitiParks Programs,Call Center,Parks & Recs-Programs,Banksville,2,20,42003202300,5,20,6,4-9,-80.035775,40.412960,APPROXIMATE
2017-06-13 12:54:00,150603,161522,2017-06-13T12:54:00,Potholes,Call Center,DPW - Street Maintenance,Beltzhoover,3,18,42003562400,4,18,3,4-21,-80.000432,40.418315,EXACT
2017-06-13 12:55:00,150604,161523,2017-06-13T12:55:00,Playground,Call Center,DPW - Park Maintenance,Point Breeze,8,14,42003140400,3,14,4,2-17,-79.918934,40.452362,EXACT
2017-06-13 13:02:00,150605,161524,2017-06-13T13:02:00,Unpermitted Electrical Work,Control Panel,"Permits, Licenses and Inspections",Squirrel Hill North,8,14,42003140300,3,14,4,2-18,-79.924497,40.439612,APPROXIMATE
2017-06-13 13:08:00,150606,161525,2017-06-13T13:08:00,Guide Rail,Website,DPW - Construction Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2017-06-13 13:09:00,150607,161526,2017-06-13T13:09:00,Referral,Call Center,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 13:16:00,150608,161527,2017-06-13T13:16:00,Potholes,Call Center,DPW - Street Maintenance,Banksville,2,20,42003202300,5,20,6,4-9,-80.048481,40.404606,EXACT
2017-06-13 13:17:00,150609,161528,2017-06-13T13:17:00,Refuse Violations,Call Center,DPW - Refuse,South Side Slopes,3,17,42003170600,4,17,3,4-5,-79.989844,40.425981,APPROXIMATE
2017-06-13 01:05:00,150453,161369,2017-06-13T01:05:00,Rodent control,Website,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020415,40.392488,APPROXIMATE
2017-06-13 00:30:00,150450,161366,2017-06-13T00:30:00,Potholes,Website,DPW - Street Maintenance,Carrick,4,29,42003290400,4,29,3,4-23,-79.982837,40.386519,EXACT
2017-06-13 00:52:00,150452,161368,2017-06-13T00:52:00,Rodent control,Website,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020291,40.392411,APPROXIMATE

In [80]:
today = datetime.datetime.today()

datetime.datetime(2017, 6, 13, 14, 40, 47, 901849)

In [82]:
pgh_311_data[today.strftime('%Y-%m-%d')]

,_id,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
CREATED_ON,,,,,,,,,,,,,,,,,
2017-06-13 00:33:00,150451,161367,2017-06-13T00:33:00,Potholes,Website,DPW - Street Maintenance,Carrick,4,29,42003290400,4,29,3,4-23,-79.982837,40.386519,EXACT
2017-06-13 08:17:00,150458,161374,2017-06-13T08:17:00,Pruning (city tree),Website,DPW - Forestry Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2017-06-13 05:01:00,150454,161370,2017-06-13T05:01:00,Rodent control,Website,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020227,40.392072,APPROXIMATE
2017-06-13 06:38:00,150455,161371,2017-06-13T06:38:00,Boat/Trailer on Street,Website,Police - Zones 1-6,Elliott,2,20,42003562600,5,20,6,1-17,-80.036531,40.444124,APPROXIMATE
2017-06-13 07:11:00,150456,161372,2017-06-13T07:11:00,Dumpster (on Street),Report2Gov Android,DPW - Permits,Knoxville,3,30,42003300100,4,30,3,4-7,-79.994010,40.411830,EXACT
2017-06-13 08:54:00,150462,161379,2017-06-13T08:54:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Homewood South,9,13,42003130400,2,13,5,3-17,-79.888215,40.452316,EXACT
2017-06-13 08:55:00,150463,161380,2017-06-13T08:55:00,Drug Enforcement,Call Center,Police - Zones 1-6,Manchester,6,21,42003210700,1,21,1,1-8,-80.023541,40.453031,APPROXIMATE
2017-06-13 08:56:00,150464,161381,2017-06-13T08:56:00,Dead Animal,Call Center,Animal Care & Control,Brighton Heights,1,27,42003270800,1,27,1,1-14,-80.033914,40.484603,EXACT
2017-06-13 08:57:00,150465,161382,2017-06-13T08:57:00,Abandoned Vehicle (parked on street),Report2Gov iOS,Police - AVU,Polish Hill,7,6,42003060500,6,6,2,2-6,-79.969192,40.456809,APPROXIMATE
2017-06-13 09:00:00,150467,161384,2017-06-13T09:00:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",South Side Slopes,3,17,42003170600,4,17,3,4-22,-79.985377,40.420779,EXACT
2017-06-13 08:58:00,150466,161383,2017-06-13T08:58:00,Barking Dog,Call Center,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020459,40.392102,APPROXIMATE
2017-06-13 08:10:00,150457,161373,2017-06-13T08:10:00,Refuse Violations,Website,DPW - Refuse,Marshall-Shadeland,1,27,42003271500,1,27,1,1-14,-80.027344,40.470608,APPROXIMATE
2017-06-13 08:52:00,150460,161377,2017-06-13T08:52:00,Litter,Call Center,DPW - Street Maintenance,Mount Washington,2,19,42003191500,5,19,3,4-27,-80.009787,40.421818,EXACT
2017-06-13 09:09:00,150468,161385,2017-06-13T09:09:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Carrick,4,29,42003290100,4,29,3,4-23,-79.995821,40.402175,EXACT
2017-06-13 08:50:00,150459,161376,2017-06-13T08:50:00,Replace/Repair a Sign,Website,DPW - Traffic,Crafton Heights,2,28,42003281400,5,28,6,1-16,-80.058813,40.449366,EXACT
2017-06-13 09:13:00,150469,161386,2017-06-13T09:13:00,"Traffic or Pedestrian Signal, Repair",Report2Gov iOS,DPW - Traffic,Knoxville,3,30,42003300100,4,30,3,4-6,-79.990578,40.415119,EXACT
2017-06-13 09:17:00,150470,161387,2017-06-13T09:17:00,Replace/Repair a Sign,Call Center,DPW - Traffic,Mount Washington,2,19,42003191400,5,19,3,4-27,-80.013081,40.422898,EXACT
2017-06-13 09:22:00,150472,161389,2017-06-13T09:22:00,Potholes,Call Center,DPW - Street Maintenance,Beechview,4,19,42003191600,5,19,6,4-28,-80.027121,40.409417,EXACT
2017-06-13 10:11:00,150493,161414,2017-06-13T10:11:00,Potholes,Call Center,DPW - Street Maintenance,Brookline,4,19,42003191900,4,19,6,4-26,-80.025885,40.396641,EXACT
2017-06-13 09:21:00,150471,161388,2017-06-13T09:21:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Beechview,4,19,42003191600,5,19,6,4-28,-80.027162,40.409320,EXACT
2017-06-13 09:30:00,150474,161390,2017-06-13T09:30:00,Water/Drinking Fountains,Website,DPW - Facilities,Shadyside,8,7,42003070800,2,7,4,3-13,-79.915491,40.455945,EXACT
2017-06-13 09:30:00,150473,161391,2017-06-13T09:30:00,Pruning (city tree),Website,DPW - Forestry Division,Squirrel Hill South,5,14,42003141400,3,14,4,2-15,-79.920236,40.423276,EXACT
2017-06-13 09:32:00,150476,161393,2017-06-13T09:32:00,Pruning (city tree),Website,DPW - Forestry Division,Squirrel Hill South,5,14,42003141400,3,14,4,2-15,-79.920022,40.423049,EXACT
2017-06-13 09:32:00,150475,161392,2017-06-13T09:32:00,Building Maintenance,Call Center,"Permits, Licenses and Inspections",Perry South,6,26,42003261500,1,26,1,1-12,-80.017832,40.470168,APPROXIMATE
2017-06-13 09:33:00,150477,161394,2017-06-13T09:33:00,Pruning (city tree),Website,DPW - Forestry Division,Squirrel Hill South,5,14,42003140800,3,14,4,2-18,-79.916081,40.437882,EXACT
2017-06-13 09:34:00,150478,161395,2017-06-13T09:34:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Central Oakland,3,4,42003040500,3,4,4,2-14,-79.955156,40.437495,EXACT
2017-06-13 09:36:00,150479,161396,2017-06-13T09:36:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Central Oakland,3,4,42003040500,3,4,4,2-14,-79.955204,40.437804,EXACT
2017-06-13 09:36:00,150480,161397,2017-06-13T09:36:00,Dead Animal,Website,Animal Care & Control,NaN,1,NaN,42003981200,NaN,NaN,NaN,NaN,-80.003643,40.446359,EXACT
2017-06-13 09:43:00,150482,161402,2017-06-13T09:43:00,Early Set Out,Website,DPW - Refuse,Allentown,3,18,42003180300,4,18,3,4-6,-79.992464,40.421079,APPROXIMATE
2017-06-13 09:58:00,150484,161404,2017-06-13T09:58:00,Overgrowth,Call Center,DPW - Street Maintenance,Elliott,2,20,42003562600,5,20,6,1-17,-80.034014,40.443576,EXACT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-06-13 12:30:00,150583,161502,2017-06-13T12:30:00,Question,Call Center,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 12:31:00,150584,161503,2017-06-13T12:31:00,Missed Pick Up,Call Center,DPW - Refuse,Terrace Village,6,5,42003051000,3,5,2,2-10,-79.971256,40.441842,APPROXIMATE
2017-06-13 12:32:00,150585,161504,2017-06-13T12:32:00,Question,Call Center,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 12:33:00,150586,161505,2017-06-13T12:33:00,Refuse Violations,Call Center,DPW - Refuse,Beechview,4,19,42003192000,5,19,6,4-28,-80.029822,40.400889,APPROXIMATE
2017-06-13 12:35:00,150587,161506,2017-06-13T12:35:00,Weeds/Debris,Website,"Permits, Licenses and Inspections",Beechview,4,19,42003192000,5,19,6,4-28,-80.019280,40.407810,EXACT
2017-06-13 12:37:00,150588,161507,2017-06-13T12:37:00,Potholes,Call Center,DPW - Street Maintenance,Beechview,4,19,42003191600,5,19,6,4-28,-80.029274,40.411929,EXACT
2017-06-13 12:39:00,150589,161508,2017-06-13T12:39:00,Potholes,Call Center,DPW - Street Maintenance,Shadyside,8,7,42003070500,2,7,4,3-11,-79.927936,40.456647,EXACT
2017-06-13 12:39:00,150590,161509,2017-06-13T12:39:00,Potholes,Call Center,DPW - Street Maintenance,Carrick,4,29,42003290100,4,29,3,4-23,-79.994601,40.394256,EXACT
2017-06-13 12:45:00,150591,161510,2017-06-13T12:45:00,Potholes,Call Center,DPW - Street Maintenance,Lincoln-Lemington-Belmar,9,12,42003120300,2,12,5,3-15,-79.904207,40.466934,EXACT
2017-06-13 12:45:00,150592,161512,2017-06-13T12:45:00,Leak,Call Center,Pittsburgh Water and Sewer Authority,Lincoln-Lemington-Belmar,9,12,42003120300,2,12,5,3-15,-79.904241,40.467019,EXACT
2017-06-13 12:45:00,150593,161511,2017-06-13T12:45:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",Bloomfield,7,8,42003080600,2,8,5,3-23,-79.942270,40.461680,EXACT
2017-06-13 12:46:00,150594,161513,2017-06-13T12:46:00,Illegal Dumping,Call Center,DPW - Permits,South Side Slopes,3,17,42003170600,4,17,3,4-3,-79.980075,40.422489,APPROXIMATE
2017-06-13 12:47:00,150595,161514,2017-06-13T12:47:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",West Oakland,6,4,42003040200,3,4,4,2-10,-79.967355,40.439866,EXACT
2017-06-13 12:48:00,150596,161515,2017-06-13T12:48:00,Overgrowth,Call Center,DPW - Street Maintenance,Carrick,4,29,42003290400,4,29,3,4-23,-79.978259,40.384019,EXACT
2017-06-13 12:49:00,150597,161516,2017-06-13T12:49:00,Potholes,Call Center,DPW - Street Maintenance,Lincoln Place,5,31,42003310200,3,31,4,4-20,-79.912357,40.370192,EXACT
2017-06-13 12:50:00,150598,161518,2017-06-13T12:50:00,"Permits, Licenses and Inspections",Website,"Permits, Licenses and Inspections",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 12:50:00,150599,161517,2017-06-13T12:50:00,Weeds/Debris,Call Center,"Permits, Licenses and Inspections",South Side Slopes,3,16,42003160800,4,16,3,4-22,-79.974084,40.421621,EXACT
2017-06-13 12:51:00,150600,161519,2017-06-13T12:51:00,Dead Animal,Twitter,Animal Care & Control,NaN,1,NaN,42003563200,NaN,NaN,NaN,NaN,-80.003425,40.445898,EXACT
2017-06-13 12:53:00,150601,161520,2017-06-13T12:53:00,Traffic,Call Center,DPW - Transportation & Engineering,South Oakland,3,4,42003980800,3,4,4,2-2,-79.959240,40.431176,EXACT
2017-06-13 12:53:00,150602,161521,2017-06-13T12:53:00,CitiParks Programs,Call Center,Parks & Recs-Programs,Banksville,2,20,42003202300,5,20,6,4-9,-80.035775,40.412960,APPROXIMATE
2017-06-13 12:54:00,150603,161522,2017-06-13T12:54:00,Potholes,Call Center,DPW - Street Maintenance,Beltzhoover,3,18,42003562400,4,18,3,4-21,-80.000432,40.418315,EXACT
2017-06-13 12:55:00,150604,161523,2017-06-13T12:55:00,Playground,Call Center,DPW - Park Maintenance,Point Breeze,8,14,42003140400,3,14,4,2-17,-79.918934,40.452362,EXACT
2017-06-13 13:02:00,150605,161524,2017-06-13T13:02:00,Unpermitted Electrical Work,Control Panel,"Permits, Licenses and Inspections",Squirrel Hill North,8,14,42003140300,3,14,4,2-18,-79.924497,40.439612,APPROXIMATE
2017-06-13 13:08:00,150606,161525,2017-06-13T13:08:00,Guide Rail,Website,DPW - Construction Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,EXACT
2017-06-13 13:09:00,150607,161526,2017-06-13T13:09:00,Referral,Call Center,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUT_OF_BOUNDS
2017-06-13 13:16:00,150608,161527,2017-06-13T13:16:00,Potholes,Call Center,DPW - Street Maintenance,Banksville,2,20,42003202300,5,20,6,4-9,-80.048481,40.404606,EXACT
2017-06-13 13:17:00,150609,161528,2017-06-13T13:17:00,Refuse Violations,Call Center,DPW - Refuse,South Side Slopes,3,17,42003170600,4,17,3,4-5,-79.989844,40.425981,APPROXIMATE
2017-06-13 01:05:00,150453,161369,2017-06-13T01:05:00,Rodent control,Website,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020415,40.392488,APPROXIMATE
2017-06-13 00:30:00,150450,161366,2017-06-13T00:30:00,Potholes,Website,DPW - Street Maintenance,Carrick,4,29,42003290400,4,29,3,4-23,-79.982837,40.386519,EXACT
2017-06-13 00:52:00,150452,161368,2017-06-13T00:52:00,Rodent control,Website,Animal Care & Control,Brookline,4,19,42003191800,4,19,6,4-26,-80.020291,40.392411,APPROXIMATE

In [ ]:


# create a Pandas datetime for today
today = pd.to_datetime("Today")

# use Pandas date string indexing to retrieve all rows for this today's date
todays_311s = pgh_311_data[str(today.date())]
todays_311s.head()

### Grouping time with the `resample` method

* Instead of using the `groupby()` method, you use the `resample()` method to *split* time into groups
* Then you can *apply* the regular aggregation functions

In [ ]:
# compute the mean of complaints per quarter...note this doesn't make sense, but works anyway
pgh_311_data.resample("Q").mean()

In [83]:
# count the number of complaints per moneth
pgh_311_data.resample("M").count()

_id                      28
REQUEST_ID               28
COUNCIL_DISTRICT         28
WARD                     28
TRACT                    28
PUBLIC_WORKS_DIVISION    28
PLI_DIVISION             27
POLICE_ZONE              28
X                        28
Y                        28
dtype: int64

* Ok, these data are *begging* to be visualized, so I'm going to give you a teaser of next week

In [85]:
# load up the data visualization libraries
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()

In [ ]:
# Create a graph of the monthly complaint counts
pgh_311_data['REQUEST_ID'].resample("M").count().plot()

Try the code above, but re-sampling based upon different date periods. The strings for specifying an offset are located [here](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)

In [ ]:
# Try a different resampling here

In [ ]:
# Try yet another resampling here

* OK, it is pretty straightforward to do stuff with Time, but maybe we want to start doing deeper analysis
* To do that, we need to know what  all these columns mean?
* Fortunately, this dataset has a [data dictionary](https://data.wprdc.org/dataset/311-data/resource/d3e98904-4a86-45fb-9041-0826ab8d56d0), which provides a bit more information.

### Exploring the 311 Data

* Now we can use what we have learned to do some exploratory data analysis on the 311 data
* First, lets use the `sample()` method to grab 10 random rows so we can get a feel for the data

In [ ]:
# Sample 10 random rows from the dataframe
pgh_311_data.sample(10)

#### Exercise


* What are the possible *origins* of complaints?
* How many complaints are coming from each source?

*HINT*: Scroll back up to the top of to look at the Dataframes refresher.

In [ ]:
pgh_311_data['REQUEST_ORIGIN'].value_counts()

#### Exercise

* *Group* the complaints *by* neighborhood and get the *size* of each group

In [ ]:
pgh_311_data.groupby('NEIGHBORHOOD').size()

In [ ]:
# Note, for just counting the groupby and value_counts are equivalent
# There is more than one way to skin the cat (or panda)
pgh_311_data['NEIGHBORHOOD'].value_counts()

#### Exercise

* *Group* the complaints *by* type and get the *count* for each group

In [ ]:
pgh_311_data.groupby("REQUEST_TYPE")['REQUEST_TYPE'].count()

This categorical data is far too granular. 
Fortunately, if we look at the [311 Data](https://data.wprdc.org/dataset/311-data) we can see there is a [311 Issue and Category Codebook](https://data.wprdc.org/dataset/311-data/resource/40ddfbed-f225-4320-b4d2-7f1e09da72a4). Click on that link and check out the Google Sheets preview of that data.

https://data.wprdc.org/dataset/311-data/resource/40ddfbed-f225-4320-b4d2-7f1e09da72a4

What we need to do is download the CSV from Google Sheets directly into a Pandas dataframe, but this is actually a bit tricky because Google won't easily give us a link to the CSV file.

In [ ]:
# I googled "pandas dataframe from google sheets"
# and found a solution on Stackoverflow
# https://stackoverflow.com/a/35246041
issue_category_mapping = pd.read_csv('https://docs.google.com/spreadsheets/d/' + 
                   '1DTDBhwXj1xQG1GCBKPqivlzHQaLh2HLd0SjN1XBPUw0' +
                   '/export?gid=0&format=csv')
issue_category_mapping.head(5)  # Same result as @TomAugspurger

#### Exercise

* Merge the `pgh_311_data` with the `issue_category_mapping` so we can count the number of complaints per category
* *HINT*: You will need to specify the `left_on` and `right_on` parameters

In [ ]:
# create a new merged dataframe
merged_311_data = pd.merge(pgh_311_data, 
         issue_category_mapping,
         left_on="REQUEST_TYPE",
         right_on="Issue")

merged_311_data.head()

In [ ]:
# get rid of redundant columns
merged_311_data.drop(['Definition','Department', 'Issue'], 
                     axis=1, 
                     inplace=True)
merged_311_data.head()

#### Exercise

* Now that we have category data, count the number of complaints by category

In [ ]:
merged_311_data.groupby("Category")['Category'].count().sort_values(ascending=False)

In [ ]:
merged_311_data.groupby("Category").size().sort_values(ascending=False)

* Selecting data in a Dateframe

In [ ]:
# Select only rows where NEIGHBORHOOD equals "Greenfield" and then count how many complaints came from each source
merged_311_data[merged_311_data['NEIGHBORHOOD'] == 'Greenfield'].groupby('REQUEST_ORIGIN').size()

## Split, Apply, Combine with numeric data

* The 311 complaints are mainly categorical data, which doesn't let use do more mathematical aggregations
* Lets grab a different dataset from the WPRDC, the [Allegheny County Jail Daily Census](https://data.wprdc.org/dataset/allegheny-county-jail-daily-census)

In [ ]:
# Grab three months of data
january_jail_census = pd.read_csv("https://data.wprdc.org/datastore/dump/3b5d9c45-b5f4-4e05-9cf1-127642ad1d17",
                                  parse_dates=True,
                                  index_col='Date')
feburary_jail_census = pd.read_csv("https://data.wprdc.org/datastore/dump/cb8dc876-6285-43a8-9db3-90b84eedb46f",
                                   parse_dates=True,
                                  index_col='Date')
march_jail_census = pd.read_csv("https://data.wprdc.org/datastore/dump/68645668-3f89-4831-b1de-de1e77e52dd3",
                                parse_dates=True,
                                index_col='Date')

In [ ]:
january_jail_census.head()

In [ ]:
# Use the concat function to combine all three into one dataframe

jail_census = pd.concat([january_jail_census, 
                         feburary_jail_census, 
                         march_jail_census])
jail_census

In [ ]:
# remove the "_id" column because it is not useful
jail_census.drop("_id", axis=1, inplace=True)
jail_census

In [ ]:
# get just the first day in Feburary
jail_census.loc["2017-02-01"]

In [ ]:
# Compute the average age ate booking by gender
jail_census.groupby('Gender')['Age at Booking'].mean()

In [ ]:
# compute the average age at booking by race
jail_census.groupby('Race')['Age at Booking'].mean()

If we look at the [data dictionary](https://data.wprdc.org/dataset/allegheny-county-jail-daily-census/resource/f0550174-16b0-4f6e-88dc-fa917e74b56c) we can see the following mapping for race categories
```
Race of Inmate
A-ASIAN OR PACIFIC ISLANDER
B-BLACK OR AFRICAN AMERICAN
H-HISPANIC 
I-AMERICAN INDIAN OR ALASKAN NATIVE
U-UNKNOWN
W-WHITE
```
The `x` category hasn't been described.

In [ ]:
# how many rows have "x" for race
jail_census['Race'].value_counts()['x']

In [ ]:
# Get the statistical summary of age at booking by gender
jail_census.groupby('Gender')['Age at Booking'].describe()

In [ ]:
# Compute the difference between Age at Booking and current age
age_difference = jail_census['Current Age'] - jail_census['Age at Booking']
age_difference.value_counts()